# ----
# Site

title: Mzansi.ai
url: https://www.mzansi.ai
baseurl:
google_analytics_key: G-XLV2D20MQ0
production: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Mzansi AI. AI stealth startup in Mzansi.
tagline: Creating search experiences for people by the people. Search difficult topics like the 2024 National Elections.
author:
  name: mzansi.ai
  email: admin@mzansi.ai
  twitter: _mzansi_ai # twitter username without the @ symbol
social:
  name: Mzansi.ai
  links:
    - https://twitter.com/_mzansi_ai
    - https://github.com/mzansi-ai

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

newsletter_action: "//your-mailchimp-action-url.com"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
